# Publish npm package trusted publisher. This closely follows the example
# provided here: https://docs.npmjs.com/trusted-publishers

name: Publish package to npmjs
on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - name: Validate tag and version
        run: node validateGitHubReleaseTag.cjs
      - run: npm ci
      - name: Install example
        run: npm i
        working-directory: ./example
      - run: npm publish --access public
